name: Publish to PyPI

on:
  workflow_dispatch:
    inputs:
      pypi_token:
        description: 'Enter your PyPI API Token'
        required: true
        type: string

jobs:
  pypi-publish:
    name: Build and publish to PyPI using Twine
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install build and twine dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: Build package (sdist and wheel)
        run: python -m build

      - name: Publish package to PyPI via twine
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ github.event.inputs.pypi_token }}
        run: twine upload dist/*
